[workspace]
members = [
  "contracts",
  "state-server",
  "types",

  "dispatcher",

  "data",
  "indexer",
  "inspect-server",
  "reader"
]

[patch.cartesi]
tx-manager = { version = "0.6", registry = "cartesi", path = "../../tx-manager/" }
