[workspace]
members = [
  "contracts",
  "data",
  "dispatcher",
  "grpc-interfaces",
  "inspect-server",
  "graphql-server",
  "rollups-events",
  "server-manager-broker-proxy",
  "state-server",
  "test-fixtures",
  "types",
]
