[workspace]
members = [
  "contracts",
  "types",

  "data",
  "indexer",
  "inspect-server",
  "reader"
]

[patch.cartesi]
state-fold = { path = "../../state-fold/state-fold" }
state-fold-types = { path = "../../state-fold/state-fold-types" }
