[workspace]
members = [
  "delegate_server",
  "offchain",
  "indexer"
]


[patch.'ssh://github.com/cartesi-corp/state-fold']
state-fold = { path = "./state-fold/state-fold" }
state-server-grpc = { path = "./state-fold/state-server-grpc" }
