[workspace]
members = [
  "delegate_server",
  "offchain",
]


[patch.'https://github.com/cartesi/state-fold']
state-fold = { path = "./state-fold/state-fold" }
state-server-grpc = { path = "./state-fold/state-server-grpc" }
