version: '3'

services:
  hardhat:
    platform: linux/amd64 # TODO: Otherwise it fails on M1
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - blockchain_data:/opt/cartesi/share/blockchain

  rollups_dispatcher:
    depends_on: [hardhat]
    build:
      context: .
      dockerfile: ./offchain/offchain/Dockerfile
    restart: always
    volumes:
      - blockchain_data:/opt/cartesi/share/blockchain
      - ./offchain/offchain:/opt/cartesi/share/config/

  statefold_server:
    depends_on: [hardhat]
    build:
      context: .
      dockerfile: ./offchain/delegate_server/Dockerfile
    restart: always
    volumes:
      - blockchain_data:/opt/cartesi/share/blockchain
      # - config:/opt/cartesi/share/config
      - ./offchain/offchain:/opt/cartesi/share/config/

        #echo_machine:

volumes:
  # config:$PWD/offchain/offchain/
  config:
  blockchain_data:
