version: '3'

services:
  hardhat:
    platform: linux/amd64 # TODO: Otherwise it fails on M1
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - blockchain_data:/opt/cartesi/share/blockchain

  rollups_dispatcher:
    depends_on: [hardhat]
    build:
      context: .
      dockerfile: ./offchain/offchain/Dockerfile
    restart: always
    environment:
      # TODO: currently hardhat's default mnemonic
      # this should become a secret
      - MNEMONIC="test test test test test test test test test test test junk"
    volumes:
      - blockchain_data:/opt/cartesi/share/blockchain
      - ./offchain/offchain:/opt/cartesi/share/config/

  statefold_server:
    depends_on: [hardhat]
    build:
      context: .
      dockerfile: ./offchain/delegate_server/Dockerfile
    restart: always
    volumes:
      - blockchain_data:/opt/cartesi/share/blockchain
      - ./offchain/offchain:/opt/cartesi/share/config/

  echo_machine:
    image: cartesicorp/rollup-echo-server:0.1.0-test2a
    restart: always
    ports:
      - "5001:5001"

volumes:
  blockchain_data:
