version: '3'

services:
  hardhat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: npx hardhat test
    ports:
     - 8545:8545

  dispatcher:
    build:
      context: .
      dockerfile: offchain/offchain/Dockerfile

  statefold_server:
    build:
      context: .
      dockerfile: ./offchain/delegate_server/Dockerfile

    # /health return 200 if healthy
