[logic_config]

# unique session identifier for machine manager
session_id = "default_rollups_id"

# node starts syncing from inital epoch
initial_epoch = 0

# gas estimation/price multiplier
gas_multiplier = 1
gas_price_multiplier = 1

# number of blocks before resubmting tx
rate = 20

# depth of blocks before considering tx finalized
confirmations = 10

# end points
signer_http_endpoint = "signer"
ws_endpoint = "ws_endpoint"
state_fold_grpc_endpoint = "state_fold_grpc_endpoint"
mm_endpoint = "mm_endpoint"
