[package]
name = "inspect-server"
license = "Apache-2.0"
version = "0.3.0"
edition = "2021"

[[bin]]
name = "inspect-server"
path = "src/main.rs"

[dependencies]
configuration = { git = "https://github.com/cartesi/offchain-utils", tag = "v0.1.0" }

actix-web = "4.1"
actix-cors = "0.6"
env_logger = "0.9"
hex = "0.4"
log = "0.4"
prost = "0.10"
serde = { version = "1.0", features = ["rc"] }
snafu = "0.6"
structopt = "0.3"
tokio = { version = "1.19", features = ["macros", "time", "rt-multi-thread"] }
tonic = "0.7"

[dev-dependencies]
reqwest = "0.11"
serial_test = "0.7"

[build-dependencies]
tonic-build = "0.7"
