[package]
name = "indexer"
license = "Apache-2.0"
version = "0.3.0"
authors = ["victornogueira <victor.nogueira@cartesi.io>"]
edition = "2018"

[[bin]]
name = "indexer_main"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
offchain-core = { git = "https://github.com/cartesi/offchain-utils", tag = "v0.1.0" }
configuration = { git = "https://github.com/cartesi/offchain-utils", tag = "v0.1.0" }
state-fold = { git = "https://github.com/cartesi/state-fold",  tag = "v0.1.0" }
offchain = { path = "../offchain" }
state-server-grpc = { git = "https://github.com/cartesi/state-fold", tag = "v0.1.0" }

ethers = { version = "0.5", features = [ "legacy", "ws" ] }
structopt = "0.3"
snafu = "0.6"
tokio = { version = "1.0", features = ["full"] }
tonic = "0.5"
serde = { version = "1.0", features = ["rc"] }
serde_json = "1.0"
prost = "0.8"
diesel = {version = "1.4", features = ["chrono", "postgres", "r2d2", "uuidv07", "serde_json"]}

[build-dependencies]
tonic-build = "0.5"
