version: '3'

services:
  hardhat:
    platform: linux/amd64 # TODO: Otherwise it fails on M1
    build:
      context: ../../
      dockerfile: Dockerfile
    restart: always
    volumes:
      - blockchain_data:/opt/cartesi/share/blockchain

  rollups_dispatcher:
    depends_on: [hardhat]
    build:
      context: ../../
      dockerfile: ./offchain/offchain/Dockerfile
    restart: always
    environment:
      # TODO: currently hardhat's default mnemonic
      # this should become a secret
      - MNEMONIC=test test test test test test test test test test test junk
      - RUST_LOG=info
      - CHAIN_ID=31337
    volumes:
      - blockchain_data:/opt/cartesi/share/blockchain
      - ../offchain:/opt/cartesi/share/config/

  statefold_server:
    depends_on: [hardhat]
    build:
      context: ../../
      dockerfile: ./offchain/delegate_server/Dockerfile
    restart: always
    environment:
      - URL=http://hardhat:8545
    volumes:
      - blockchain_data:/opt/cartesi/share/blockchain
      - ../offchain:/opt/cartesi/share/config/

  echo_machine:
    image: cartesicorp/host-server-manager:0.1.0
    environment:
      - DAPP_HTTP_ADDRESS=host.docker.internal
    ports:
      - "5001:5001"
    restart: always

  polling_writing:
    depends_on: [hardhat]
    build:
      context: ../../ 
      dockerfile: ./offchain/polling-writing/Dockerfile
    restart: always
    environment:
      - URL=http://hardhat:8545
    volumes:
      - blockchain_data:/opt/cartesi/share/blockchain
      - ./:/opt/cartesi/share/config/
        
  app:
    env_file: ../../src/reader/.env
    build: ../../src/reader/
    command: bash -c "yarn run migrate; yarn start"
    volumes:
      - ../../src/reader/:/code
    ports:
      - '4000:4000'
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres:12
    ports:
      - 5432:5432
    env_file: ../../src/reader/.env
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  blockchain_data:
  database-data: {}
