[polling_config]

# unique session identifier for machine manager
session_id = "default_rollups_id"

# node starts syncing from inital epoch
initial_epoch = 0

# node starts syncing from epoch index
epoch_index = 0

# polling interval
interval = 10

rollups_contract_address = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"

# end points
postgres_endpoint = "postgres://postgres:password@database/postgres"
state_server_endpoint = "http://statefold_server:50051"
mm_endpoint = "http://echo_machine:5000"
