[package]
name = "types"
version = "0.1.0"
edition = "2021"

[dependencies]
state-fold = { version = "0.3", registry = "cartesi" }
state-fold-types = { version = "0.3", registry = "cartesi", features = ["ethers"] }

anyhow = "1"
async-trait = "0.1"
contracts = { path = "../contracts" }
im = { version = "15", features = ["serde"] }
serde = { version = "1", features = ["rc"] }
