[profile.default]
src = 'contracts'
out = 'out'
libs = ['../node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'
solc_version = '0.8.19'

# See more config options https://book.getfoundry.sh/reference/config.html
