# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Code Format
on: [push]
jobs:
    onchain:
        runs-on: ubuntu-20.04
        defaults:
            run:
                working-directory: onchain
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "16"
            - run: yarn install
            - run: yarn prettier:rollups
            - run: yarn prettier:hardhat-rollups
    
    offchain:
        runs-on: ubuntu-20.04
        defaults:
            run:
                working-directory: offchain
        steps:
            - uses: actions/checkout@v2
            - run: cargo fmt --all -- --check
