# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Dispatcher
on:
  pull_request:
    paths:
      - offchain/offchain/**
      - grpc-interfaces/**
      - onchain/rollups/abi/**
      - .github/workflows/dispatcher.yml
      - .github/workflows/docker.yml
  push:
    tags:
      - v*
    branches:
      - develop
jobs:
  image:
    uses: ./.github/workflows/docker.yml
    with:
      target: dispatcher
      image-name: rollups-dispatcher
    secrets: inherit
