# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Inspect Server
on:
  pull_request:
    paths:
      - offchain/inspect-server/**
      - grpc-interfaces/**
      - .github/workflows/inspect-server.yml
  push:
    tags:
      - v*
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Run tests
        run: cargo test
        working-directory: offchain/inspect-server

  image:
    needs: test
    uses: ./.github/workflows/docker.yml
    with:
      target: inspect-server 
      image-name: rollups-inspect-server
    secrets: inherit
